/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ThreatCategory = IDL.Variant({
  'AmplificationRisk' : IDL.Null,
  'EncryptionRisk' : IDL.Null,
  'NameserverLegitimacy' : IDL.Null,
  'TldRisk' : IDL.Null,
  'DnssecRisk' : IDL.Null,
  'HijackingRisk' : IDL.Null,
});
export const CategoryScore = IDL.Record({
  'score' : IDL.Nat,
  'details' : IDL.Text,
  'category' : ThreatCategory,
  'passed' : IDL.Bool,
});
export const DomainAnalysis = IDL.Record({
  'overallScore' : IDL.Nat,
  'domain' : IDL.Text,
  'rawDnsJson' : IDL.Text,
  'checkedAt' : Timestamp,
  'categoryScores' : IDL.Vec(CategoryScore),
});
export const ComparisonResult = IDL.Record({
  'exportedAt' : Timestamp,
  'domainA' : DomainAnalysis,
  'domainB' : DomainAnalysis,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'analyzeDomain' : IDL.Func([IDL.Text], [DomainAnalysis], []),
  'clearCache' : IDL.Func([IDL.Text], [], []),
  'compareDomains' : IDL.Func([IDL.Text, IDL.Text], [ComparisonResult], []),
  'exportComparison' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getCachedAnalysis' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DomainAnalysis)],
      ['query'],
    ),
  'listAnalysedDomains' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ThreatCategory = IDL.Variant({
    'AmplificationRisk' : IDL.Null,
    'EncryptionRisk' : IDL.Null,
    'NameserverLegitimacy' : IDL.Null,
    'TldRisk' : IDL.Null,
    'DnssecRisk' : IDL.Null,
    'HijackingRisk' : IDL.Null,
  });
  const CategoryScore = IDL.Record({
    'score' : IDL.Nat,
    'details' : IDL.Text,
    'category' : ThreatCategory,
    'passed' : IDL.Bool,
  });
  const DomainAnalysis = IDL.Record({
    'overallScore' : IDL.Nat,
    'domain' : IDL.Text,
    'rawDnsJson' : IDL.Text,
    'checkedAt' : Timestamp,
    'categoryScores' : IDL.Vec(CategoryScore),
  });
  const ComparisonResult = IDL.Record({
    'exportedAt' : Timestamp,
    'domainA' : DomainAnalysis,
    'domainB' : DomainAnalysis,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'analyzeDomain' : IDL.Func([IDL.Text], [DomainAnalysis], []),
    'clearCache' : IDL.Func([IDL.Text], [], []),
    'compareDomains' : IDL.Func([IDL.Text, IDL.Text], [ComparisonResult], []),
    'exportComparison' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getCachedAnalysis' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DomainAnalysis)],
        ['query'],
      ),
    'listAnalysedDomains' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };