/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CategoryScore {
    score: bigint;
    details: string;
    category: ThreatCategory;
    passed: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DomainAnalysis {
    overallScore: bigint;
    domain: string;
    rawDnsJson: string;
    checkedAt: Timestamp;
    categoryScores: Array<CategoryScore>;
}
export interface ComparisonResult {
    exportedAt: Timestamp;
    domainA: DomainAnalysis;
    domainB: DomainAnalysis;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum ThreatCategory {
    AmplificationRisk = "AmplificationRisk",
    EncryptionRisk = "EncryptionRisk",
    NameserverLegitimacy = "NameserverLegitimacy",
    TldRisk = "TldRisk",
    DnssecRisk = "DnssecRisk",
    HijackingRisk = "HijackingRisk"
}
export interface backendInterface {
    analyzeDomain(domain: string): Promise<DomainAnalysis>;
    clearCache(domain: string): Promise<void>;
    compareDomains(domainA: string, domainB: string): Promise<ComparisonResult>;
    exportComparison(domainA: string, domainB: string): Promise<string>;
    getCachedAnalysis(domain: string): Promise<DomainAnalysis | null>;
    listAnalysedDomains(): Promise<Array<string>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { CategoryScore as _CategoryScore, ComparisonResult as _ComparisonResult, DomainAnalysis as _DomainAnalysis, ThreatCategory as _ThreatCategory, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeDomain(arg0: string): Promise<DomainAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeDomain(arg0);
                return from_candid_DomainAnalysis_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeDomain(arg0);
            return from_candid_DomainAnalysis_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearCache(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCache(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCache(arg0);
            return result;
        }
    }
    async compareDomains(arg0: string, arg1: string): Promise<ComparisonResult> {
        if (this.processError) {
            try {
                const result = await this.actor.compareDomains(arg0, arg1);
                return from_candid_ComparisonResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareDomains(arg0, arg1);
            return from_candid_ComparisonResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportComparison(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportComparison(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportComparison(arg0, arg1);
            return result;
        }
    }
    async getCachedAnalysis(arg0: string): Promise<DomainAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedAnalysis(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedAnalysis(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnalysedDomains(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalysedDomains();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalysedDomains();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_CategoryScore_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryScore): CategoryScore {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ComparisonResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComparisonResult): ComparisonResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DomainAnalysis_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DomainAnalysis): DomainAnalysis {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatCategory): ThreatCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DomainAnalysis]): DomainAnalysis | null {
    return value.length === 0 ? null : from_candid_DomainAnalysis_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overallScore: bigint;
    domain: string;
    rawDnsJson: string;
    checkedAt: _Timestamp;
    categoryScores: Array<_CategoryScore>;
}): {
    overallScore: bigint;
    domain: string;
    rawDnsJson: string;
    checkedAt: Timestamp;
    categoryScores: Array<CategoryScore>;
} {
    return {
        overallScore: value.overallScore,
        domain: value.domain,
        rawDnsJson: value.rawDnsJson,
        checkedAt: value.checkedAt,
        categoryScores: from_candid_vec_n3(_uploadFile, _downloadFile, value.categoryScores)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: bigint;
    details: string;
    category: _ThreatCategory;
    passed: boolean;
}): {
    score: bigint;
    details: string;
    category: ThreatCategory;
    passed: boolean;
} {
    return {
        score: value.score,
        details: value.details,
        category: from_candid_ThreatCategory_n6(_uploadFile, _downloadFile, value.category),
        passed: value.passed
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exportedAt: _Timestamp;
    domainA: _DomainAnalysis;
    domainB: _DomainAnalysis;
}): {
    exportedAt: Timestamp;
    domainA: DomainAnalysis;
    domainB: DomainAnalysis;
} {
    return {
        exportedAt: value.exportedAt,
        domainA: from_candid_DomainAnalysis_n1(_uploadFile, _downloadFile, value.domainA),
        domainB: from_candid_DomainAnalysis_n1(_uploadFile, _downloadFile, value.domainB)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AmplificationRisk: null;
} | {
    EncryptionRisk: null;
} | {
    NameserverLegitimacy: null;
} | {
    TldRisk: null;
} | {
    DnssecRisk: null;
} | {
    HijackingRisk: null;
}): ThreatCategory {
    return "AmplificationRisk" in value ? ThreatCategory.AmplificationRisk : "EncryptionRisk" in value ? ThreatCategory.EncryptionRisk : "NameserverLegitimacy" in value ? ThreatCategory.NameserverLegitimacy : "TldRisk" in value ? ThreatCategory.TldRisk : "DnssecRisk" in value ? ThreatCategory.DnssecRisk : "HijackingRisk" in value ? ThreatCategory.HijackingRisk : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryScore>): Array<CategoryScore> {
    return value.map((x)=>from_candid_CategoryScore_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
